export const AUTH_SIGN_UP_REQUEST = `AUTH_SIGN_UP_REQUEST`;
export const AUTH_SIGN_UP_SUCCESS = `AUTH_SIGN_UP_SUCCESS`;
export const AUTH_SIGN_UP_FAIL = `AUTH_SIGN_UP_FAIL`;

export const AUTH_SIGN_IN_REQUEST = `AUTH_SIGN_IN_REQUEST`;
export const AUTH_SIGN_IN_SUCCESS = `AUTH_SIGN_IN_SUCCESS`;
export const AUTH_SIGN_IN_FAIL = `AUTH_SIGN_IN_FAIL`;
export const AUTH_SIGN_OUT = `AUTH_SIGN_OUT`;

export const AUTH_VERIFY_ACCOUNT_REQUEST = `AUTH_VERIFY_ACCOUNT_REQUEST`;
export const AUTH_VERIFY_ACCOUNT_SUCCESS = `AUTH_VERIFY_ACCOUNT_SUCCESS`;
export const AUTH_VERIFY_ACCOUNT_FAIL = `AUTH_VERIFY_ACCOUNT_FAIL`;

export const AUTH_FORGOT_PASSWORD_REQUEST = `AUTH_FORGOT_PASSWORD_REQUEST`;
export const AUTH_FORGOT_PASSWORD_SUCCESS = `AUTH_FORGOT_PASSWORD_SUCCESS`;
export const AUTH_FORGOT_PASSWORD_FAIL = `AUTH_FORGOT_PASSWORD_FAIL`;

export const AUTH_RESET_PASSWORD_REQUEST = `AUTH_RESET_PASSWORD_REQUEST`;
export const AUTH_RESET_PASSWORD_SUCCESS = `AUTH_RESET_PASSWORD_SUCCESS`;
export const AUTH_RESET_PASSWORD_FAIL = `AUTH_RESET_PASSWORD_FAIL`;

export const AUTH_GOOGLE_REQUEST = `AUTH_GOOGLE_REQUEST`;
export const AUTH_GOOGLE_SUCCESS = `AUTH_GOOGLE_SUCCESS`;
export const AUTH_GOOGLE_FAIL = `AUTH_GOOGLE_FAIL`;

export const AUTH_REVOKE_TOKEN_REQUEST = `AUTH_REVOKE_TOKEN_REQUEST`;
export const AUTH_REVOKE_TOKEN_SUCCESS = `AUTH_REVOKE_TOKEN_SUCCESS`;
export const AUTH_REVOKE_TOKEN_FAIL = `AUTH_REVOKE_TOKEN_FAIL`;
